### PR TITLE
Support evaluating multiple checkpoints for same model

### PR DESCRIPTION
**Pull request by rwightman**
* use --pretrained_glob to eval multiple checkpoints for same model via glob pattern
* don't dump single result output files if --output is set to ''
* output all results in one summary json if --output-summary is set
* canonical imports order

### CODE REVIEW

**Comment by mehdidc** [comment]
Great, works fine, LGTM. 
Could you maybe just add a a doc in the README here https://github.com/LAION-AI/CLIP_benchmark#evaluate-mulitple-models-on-multiple-datasets, on a subsection?

**Comment by rwightman** [comment]
@mehdidc okay, I'll revisit the ski behaviour with that info in mind, I guess it'd also be useful to be able to continue evaluating the summary output file (load json, append, re-save), will see if that can be added too

**Comment by mehdidc** [comment]
Ok great, thanks a lot

**Comment by rwightman** [comment]
@mehdidc ended up pulling the slug/output file and key formatting so it was easier to share without passing more into run() ... skipping seemed to be working, and can append to an existing summary file (checks by key)

**Comment by mehdidc** [comment]
Thanks a lot @rwightman , was just testing it, working great.
There is one case where `args.output` is provided and `skip_existing` is True, I'd say before `continue` there should be something like `all[run_key] = json.load(open(output))` to fill the summary with the existing result. Happened to me actually, I ran first and forgot to use `--output_summary`, but then wanted the summary, but without re-running again. So w.r.t  to your comment, I'd still allow skipping if both `--output_summary` or `--output` are provided, or do you see a downside there?

**Comment by rom1504** [comment]
can you rebase on main ?

**Comment by rwightman** [comment]
@rom1504 I looked at it, but too far gone to merge cleanly and using this locally to eval, bit of work to re-do and verify...

**Comment by rwightman** [comment]
yeah, merge will take longer than redoing, so closing this, maybe get a chance next week.

**Comment by rwightman** [comment]
also, @mehdidc that last comment wasn't clear, it was supposed to skip if either output summary is used and dict key not in summary, or --output is specified and the output file exists, if you started with just --output and then add --output-summary it should still skip the files that already have output files

it would not do waht was expected if you changed the args output/output-summary args after you started eval, and it would not 'move' the existing results into the summary from output files, but that seems not worth the code / main given it only happens in transition

**Pull request closed without merging**
