### PR TITLE
Webdataset updates

### PR DESCRIPTION
**Pull request by djghosh13**
(Mostly) addresses issues #52 and #67 

* Support for conversion and evaluation of retrieval datasets (`clip_benchmark_export_wds --retrieval`)
* More complete API for converting other classification/retrieval datasets, with `import clip_benchmark.webdataset_builder`)
* (Not in commit) All VTAB+ and retrieval datasets have been uploaded to [HF](https://huggingface.co/clip-benchmark)
* Readmes have been updated appropriately, default suggestion in `benchmark/README.md` is to use webdataset

Not completed:
* Multilingual support, i.e., overriding default classnames & templates with other languages
* Converting `voc2007_multilabel`

### CODE REVIEW

**Comment by djghosh13** [comment]
Note: I've only tested the benchmark code with a single model, so I haven't run the complete experiments. There are some minor differences in numbers from what @rom1504 gave me, but no differences from what I get with the original datasets when I run them myself.

**Comment by rom1504** [comment]
Nice, will check it out

**Comment by mehdidc** [comment]
Really cool, thanks @djghosh13! For differences in numbers, might be related to this issue https://github.com/LAION-AI/CLIP_benchmark/issues/59

**Comment by djghosh13** [comment]
I see, yeah, I think the differences I saw were also in the 0.001s range.

**Comment by rom1504** [comment]
Are datasets getting cached locally? Where and is it tweakable ?

**Comment by djghosh13** [comment]
I forgot to add this to the readme. By default, no, but there is a new `--wds_cache_dir` parameter in the CLI which is directly passed to `Webdataset(cache_dir=)` if a path is given.

**Comment by djghosh13** [comment]
I hadn't actually tested it before, but it looks like it will save the .tar files inside the specified cache directory in a subdirectory that's named like `datasets_clip-benchmark_wds_vtab-cifar10_resolve_main_test` (for example)

**Comment by rom1504** [comment]
ok if it doesn't by default, it's good

**Comment by rom1504** [comment]
I'll test this

**Comment by rom1504** [comment]
ok so one thing here
not caused by your pr, but I really think we should put the main eval command in the readme at the beginning, not hidden in benchmark/ folder

**Comment by rom1504** [comment]
https://github.com/LAION-AI/CLIP_benchmark/issues/76 a minor point, but quite nice for UX

**Comment by rom1504** [comment]
yeah this is much faster than the file based option

will run to the end and compare numbers, if all good will merge

**Comment by rom1504** [comment]
ok it does work, let's go

**Pull request merged**
